# docker-compose.yml
version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root123
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret123
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
